### ISSUE TITLE
feature: bigger tolerance for snap when bases intersect

### ISSUE THREAD

**Issue by marcpawl** [leberechtreinhold/dba3_tts#13]
As a user I want to make snapping easier so the game is faster to play and less finicky.

If dropping a base, the base intersects with a new one, the this is an invalid position.  More than likely the user is trying to snap the bases.  When there is an intersection increase the radius used to detect snapping.

**Comment by marcpawl** [comment]
I will be working on this one in a private repo.

**Comment by leberechtreinhold** [comment]
Great, thanks! This will be very useful. You can make a fork and make a pullrequest or any other workflow than you like.

**Comment by leberechtreinhold** [comment]
This has been added on your pull request, works great and with the cache is very useful.
I have toyed a bit with it and I think g_max_corner_distance_snap_intersect = 0.8 is even better than 0.6, but I would rather ask first if there may be an issue with it... Looking at the code seems like no problem (although a bit more than that and I think we would run into problems of stacking in formation, since 0.8 is already half a base).
